#!/usr/bin/env python3
"""
Skill rule validator — PostToolUse hook for Claude Code.

After a skill completes, this script:
1. Runs a compiled validator (validator.py next to SKILL.md) — < 1s
2. Optionally chains semantic validation (--semantic) via a small LLM
   for the subset of rules that require human-level judgment

Compiled validators are generated by the /compile-validators skill and check
MUST/NEVER/CHECKLIST rules deterministically using validator_lib.py.

The main agent receives violations on stderr and must fix them
before the skill is considered complete.

Exit codes:
  0 — all rules satisfied (or nothing to check)
  2 — violations found (stderr contains details for the agent)
  1 — script error (non-blocking, logged but doesn't block agent)

Usage:
  # As a Claude Code hook (reads JSON from stdin):
  echo '{"tool_name":"Skill","tool_input":{"skill":"concept-2-experience-4-storybook"},"cwd":"/path/to/project"}' | python3 validate_skill_rules.py

  # Direct invocation for testing:
  python3 validate_skill_rules.py --skill concept-2-experience-4-storybook --cwd /path/to/project

  # Compiled + semantic: structural checks fast, then LLM for skipped rules:
  python3 validate_skill_rules.py --skill concept-1-discovery-3-brand --cwd /path/to/project --semantic

  # With custom timeout (seconds, default 300):
  python3 validate_skill_rules.py --skill concept-2-experience-1-journeys --cwd /path/to/project --timeout 120

  # Verbose mode (show prompts and full LLM responses):
  python3 validate_skill_rules.py --skill concept-2-experience-1-journeys --cwd /path/to/project --verbose

  # Use a different model for semantic validation (default: haiku):
  python3 validate_skill_rules.py --skill concept-2-experience-1-journeys --cwd /path/to/project --semantic --model sonnet
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import threading
import time
from pathlib import Path


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Max files to send to the semantic validator (avoid token explosion)
MAX_FILES = 40

# Default max characters per file — overridable via --max-file-size
MAX_FILE_SIZE_DEFAULT = 50000

# File extensions to read from output directories
CODE_EXTENSIONS = {
    ".tsx", ".ts", ".jsx", ".js", ".json", ".css", ".md",
    ".html", ".yaml", ".yml", ".toml", ".mjs", ".cjs",
}

# Default timeout for claude -p call (seconds) — overridable via --timeout
CLAUDE_TIMEOUT_DEFAULT = 300


# ---------------------------------------------------------------------------
# Skill discovery
# ---------------------------------------------------------------------------

SKILL_SUBDIRS = ["concept", "implement", "support"]


def find_skill_md(skill_name: str, project_root: Path) -> Path | None:
    """Locate the SKILL.md for a given skill name."""
    for subdir in SKILL_SUBDIRS:
        candidate = project_root / "skills" / subdir / skill_name / "SKILL.md"
        if candidate.exists():
            return candidate
    return None


def find_compiled_validator(skill_name: str, project_root: Path) -> Path | None:
    """Locate a compiled validator.py for a given skill."""
    for subdir in SKILL_SUBDIRS:
        candidate = project_root / "skills" / subdir / skill_name / "validator.py"
        if candidate.exists():
            return candidate
    return None


# ---------------------------------------------------------------------------
# Compiled validator execution
# ---------------------------------------------------------------------------

def run_compiled_validator(validator_path: Path, cwd: Path,
                           timeout: int = 30) -> dict | None:
    """Run a compiled validator and return its JSON result.

    Returns None on error.
    """
    scripts_dir = validator_path.parent.parent.parent / "shared" / "scripts"
    env = os.environ.copy()
    env["PYTHONPATH"] = str(scripts_dir) + os.pathsep + env.get("PYTHONPATH", "")

    try:
        result = subprocess.run(
            [sys.executable, str(validator_path), "--cwd", str(cwd), "--json"],
            capture_output=True, text=True, timeout=timeout, env=env,
        )
        stdout = result.stdout.strip()
        if stdout:
            return json.loads(stdout)
        if result.returncode not in (0, 2):
            if result.stderr.strip():
                print(f"  stderr: {result.stderr.strip()[:300]}", file=sys.stderr, flush=True)
        return None
    except subprocess.TimeoutExpired:
        print(f"⚠ Compiled validator timed out after {timeout}s", file=sys.stderr, flush=True)
        return None
    except json.JSONDecodeError as e:
        print(f"⚠ Compiled validator returned invalid JSON: {e}", file=sys.stderr, flush=True)
        return None
    except Exception as e:
        print(f"⚠ Compiled validator error: {e}", file=sys.stderr, flush=True)
        return None


def format_compiled_result(result: dict, skill_md: Path | None = None,
                           exit_after: bool = True) -> None:
    """Print compiled validator results.

    If *exit_after* is True, exits with 0 (PASS) or 2 (FAIL).
    If False, prints the report but returns so the caller can chain
    semantic validation for skipped rules.
    """
    skill = result.get("skill", "unknown")
    verdict = result.get("verdict", "UNKNOWN")
    passed = result.get("passed", 0)
    skipped = result.get("skipped", 0)
    violations = result.get("violations", [])

    if verdict == "PASS":
        print(
            f"✅ Structural validation PASSED for '{skill}' "
            f"({passed} checks passed, {skipped} skipped)"
        )
        if exit_after:
            sys.exit(0)
    else:
        report = (
            f"❌ Skill rule validation FAILED for '{skill}'\n\n"
            f"The following rules were violated:\n\n"
        )
        for v in violations:
            report += f"  VIOLATION: [{v['type']}] {v['rule']} — {v['detail']}\n"

        report += f"\nFix these violations before proceeding.\n"
        if skill_md:
            report += f"Rules source: {skill_md}\n"

        skipped_rules = result.get("skipped_rules", [])
        if skipped_rules:
            report += f"\n⚠ {skipped} rules skipped (require human review):\n"
            for s in skipped_rules:
                report += f"  [{s['type']}] {s['rule']}\n"

        print(report, file=sys.stderr)
        if exit_after:
            sys.exit(2)


# ---------------------------------------------------------------------------
# SKILL.md parsing (WRITES paths only — needed for output detection)
# ---------------------------------------------------------------------------

def extract_writes(skill_md: Path) -> list[str]:
    """Extract WRITES paths from SKILL.md."""
    text = skill_md.read_text(encoding="utf-8")
    paths = []
    in_writes = False

    for line in text.splitlines():
        stripped = line.strip()

        if stripped.startswith("WRITES"):
            in_writes = True
            continue

        if in_writes:
            if stripped and re.match(
                r"^(READS|REFERENCES|REQUIRES|MUST|NEVER|STEP|ROLE|EMIT|CHECKLIST|PROCEDURE|PATTERNS|OUTPUT)\b",
                stripped,
            ):
                break

            if stripped.startswith("_concept") or stripped.startswith("_implementation"):
                path = stripped.split("—")[0].split("#")[0].strip()
                if path:
                    paths.append(path)

    return paths


# ---------------------------------------------------------------------------
# Output file collection (used by semantic validation)
# ---------------------------------------------------------------------------

def collect_output_files(writes: list[str], cwd: Path, max_file_size: int) -> dict[str, str]:
    """
    Read output files from WRITES paths.
    Returns {relative_path: content} dict, respecting size limits.
    """
    files = {}

    for write_path in writes:
        full_path = cwd / write_path

        if full_path.is_file():
            _read_file(full_path, cwd, files, max_file_size)

        elif full_path.is_dir():
            candidates = sorted(full_path.rglob("*"))
            for f in candidates:
                if len(files) >= MAX_FILES:
                    break
                if f.is_file() and f.suffix in CODE_EXTENSIONS:
                    _read_file(f, cwd, files, max_file_size)

    if not files:
        files = _collect_from_git(cwd, max_file_size)

    return files


def _read_file(filepath: Path, cwd: Path, files: dict, max_file_size: int):
    """Read a single file into the files dict with truncation."""
    rel = str(filepath.relative_to(cwd))
    try:
        content = filepath.read_text(encoding="utf-8")
        if len(content) > max_file_size:
            content = content[:max_file_size] + f"\n\n... [truncated at {max_file_size} chars]"
        files[rel] = content
    except Exception:
        pass


def _collect_from_git(cwd: Path, max_file_size: int) -> dict[str, str]:
    """Fallback: collect modified/untracked files from git status."""
    files = {}
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", "HEAD"],
            capture_output=True, text=True, cwd=cwd, timeout=10,
        )
        modified = result.stdout.strip().splitlines()

        result2 = subprocess.run(
            ["git", "ls-files", "--others", "--exclude-standard"],
            capture_output=True, text=True, cwd=cwd, timeout=10,
        )
        untracked = result2.stdout.strip().splitlines()

        for rel in (modified + untracked)[:MAX_FILES]:
            fp = cwd / rel
            if fp.is_file() and fp.suffix in CODE_EXTENSIONS:
                _read_file(fp, cwd, files, max_file_size)

    except Exception:
        pass

    return files


# ---------------------------------------------------------------------------
# Semantic validation (LLM for skipped rules only)
# ---------------------------------------------------------------------------

def build_semantic_prompt(skipped_rules: list[dict], files: dict,
                          skill_name: str) -> str:
    """Build a focused LLM prompt for ONLY the semantic/skipped rules.

    Much smaller than a full-rules prompt — typically 5-15 rules instead of
    20+, and the instructions are tighter since structural checks already
    passed.
    """
    prompt = f"""You are a quality reviewer for the "{skill_name}" skill.
Structural rules (file existence, JSON fields, frontmatter, naming) have already
PASSED automated checks. Your job is to evaluate ONLY the semantic/subjective
rules below that require human-level judgment.

## Semantic rules to evaluate ({len(skipped_rules)} total)

"""
    for i, rule in enumerate(skipped_rules, 1):
        prompt += f"{i}. [{rule['type']}] {rule['rule']}\n"

    prompt += f"\n## Output files ({len(files)} files)\n\n"

    for path, content in files.items():
        prompt += f"### {path}\n```\n{content}\n```\n\n"

    prompt += """## Instructions

For each semantic rule, assess whether the output demonstrates compliance:
- Quality rules ("generic", "cookie-cutter"): look for specificity, domain awareness, unique choices
- Content rules ("focus on X", "justify Y"): look for relevant content, reasoning, depth
- Process rules ("discuss with user", "cite sources"): SKIP — cannot verify from files alone

Be generous on borderline cases — these are subjective. Only flag clear violations.

## Output format

Start with EXACTLY one of:
  VERDICT: PASS
  VERDICT: FAIL

If FAIL, list each violation:
  VIOLATION: [MUST|NEVER] <rule summary> — <what's wrong> — File: <path or "N/A">

Keep it concise.
"""
    return prompt


def run_semantic_validation(
    skipped_rules: list[dict], skill_name: str, skill_md: Path,
    cwd: Path, model: str, timeout: int, max_file_size: int,
    verbose: bool,
) -> None:
    """Run LLM validation for semantic/skipped rules only.

    Collects output files, builds a focused prompt, and calls claude -p.
    Exits 0 (PASS) or 2 (FAIL).
    """
    # Filter out rules the LLM can't check either
    checkable = [r for r in skipped_rules
                 if "process" not in r.get("reason", "").lower()
                 and "runtime" not in r.get("reason", "").lower()
                 and "visual" not in r.get("reason", "").lower()
                 and "conditional" not in r.get("reason", "").lower()]

    if not checkable:
        print(
            f"  ℹ All {len(skipped_rules)} skipped rules are process/runtime "
            f"— nothing for LLM to check",
            file=sys.stderr, flush=True,
        )
        sys.exit(0)

    # Collect output files
    writes = extract_writes(skill_md)
    files = collect_output_files(writes, cwd, max_file_size)

    if not files:
        print(
            f"  ⚠ No output files for semantic validation",
            file=sys.stderr, flush=True,
        )
        sys.exit(0)

    prompt = build_semantic_prompt(checkable, files, skill_name)

    print(
        f"  🧠 Semantic validation: {len(checkable)} rules via claude -p "
        f"--model {model} ({len(prompt)} chars, {len(files)} files)...",
        file=sys.stderr, flush=True,
    )

    if verbose:
        print(f"\n{'='*60}", file=sys.stderr, flush=True)
        print(f"SEMANTIC PROMPT ({len(prompt)} chars):", file=sys.stderr, flush=True)
        print(f"{'='*60}", file=sys.stderr, flush=True)
        print(prompt[:2000] + ("\n... [truncated]" if len(prompt) > 2000 else ""),
              file=sys.stderr, flush=True)
        print(f"{'='*60}\n", file=sys.stderr, flush=True)

    # Call claude -p
    output = ""
    try:
        cmd = ["claude", "-p", "--output-format", "text", "--model", model]
        proc = subprocess.Popen(
            cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.PIPE, text=True, cwd=str(cwd),
        )
        proc.stdin.write(prompt)
        proc.stdin.close()

        stdout_chunks: list[str] = []
        stderr_chunks: list[str] = []
        start_time = time.time()

        def _read(stream, chunks):
            try:
                for line in stream:
                    chunks.append(line)
            except Exception:
                pass

        t1 = threading.Thread(target=_read, args=(proc.stdout, stdout_chunks), daemon=True)
        t2 = threading.Thread(target=_read, args=(proc.stderr, stderr_chunks), daemon=True)
        t1.start()
        t2.start()

        while proc.poll() is None:
            elapsed = int(time.time() - start_time)
            if elapsed > 0 and elapsed % 10 == 0:
                print(f"  ... {elapsed}s elapsed", file=sys.stderr, flush=True)
            if elapsed >= timeout:
                proc.kill()
                proc.wait()
                print(f"  ⚠ Semantic validation timed out after {timeout}s",
                      file=sys.stderr, flush=True)
                sys.exit(1)
            time.sleep(1)

        t1.join(timeout=5)
        t2.join(timeout=5)
        output = "".join(stdout_chunks).strip()
        elapsed = int(time.time() - start_time)
        print(f"  ✓ Semantic validation returned in {elapsed}s", file=sys.stderr, flush=True)

    except FileNotFoundError:
        print("  ⚠ 'claude' CLI not found — skipping semantic validation",
              file=sys.stderr, flush=True)
        sys.exit(0)

    if not output:
        print("  ⚠ Semantic validation returned empty output",
              file=sys.stderr, flush=True)
        sys.exit(1)

    if verbose:
        print(f"\n{'='*60}", file=sys.stderr, flush=True)
        print("SEMANTIC RESPONSE:", file=sys.stderr, flush=True)
        print(output, file=sys.stderr, flush=True)
        print(f"{'='*60}\n", file=sys.stderr, flush=True)

    # Parse verdict
    if "VERDICT: PASS" in output:
        print(f"✅ Semantic validation PASSED ({len(checkable)} rules checked by LLM)")
        sys.exit(0)
    elif "VERDICT: FAIL" in output:
        violations = [l.strip() for l in output.splitlines()
                      if l.strip().startswith("VIOLATION:") or
                         l.strip().startswith("- VIOLATION:")]
        report = (
            f"❌ Semantic validation FAILED for '{skill_name}'\n\n"
            f"The following semantic rules were violated:\n\n"
        )
        for v in violations:
            report += f"  {v}\n"
        fixes_start = output.find("## Suggested fixes")
        if fixes_start == -1:
            fixes_start = output.find("## Suggested Fixes")
        if fixes_start >= 0:
            report += f"\n{output[fixes_start:]}\n"
        report += f"\nFix these semantic violations before proceeding.\n"
        print(report, file=sys.stderr)
        sys.exit(2)
    else:
        print(f"  ⚠ Semantic validation: ambiguous result\n{output[:300]}",
              file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_cli_arg(flag: str) -> str | None:
    """Parse a --flag value from sys.argv."""
    if flag in sys.argv:
        idx = sys.argv.index(flag)
        return sys.argv[idx + 1] if idx + 1 < len(sys.argv) else None
    return None


def main():
    # --- Parse input ---
    # Support both stdin (hook mode) and CLI args (testing mode)
    skill_name = parse_cli_arg("--skill")
    cwd = parse_cli_arg("--cwd")
    timeout_str = parse_cli_arg("--timeout")
    verbose = "--verbose" in sys.argv or "-v" in sys.argv
    semantic = "--semantic" in sys.argv

    max_file_size_str = parse_cli_arg("--max-file-size")
    model = parse_cli_arg("--model") or "haiku"

    claude_timeout = int(timeout_str) if timeout_str else CLAUDE_TIMEOUT_DEFAULT
    max_file_size = int(max_file_size_str) if max_file_size_str else MAX_FILE_SIZE_DEFAULT

    if not skill_name:
        # Hook mode: read from stdin
        try:
            hook_input = json.load(sys.stdin)
        except (json.JSONDecodeError, ValueError):
            sys.exit(0)  # Can't parse input, skip silently

        tool_name = hook_input.get("tool_name", "")
        if tool_name != "Skill":
            sys.exit(0)

        tool_input = hook_input.get("tool_input", {})
        skill_name = tool_input.get("skill", "")
        if not skill_name:
            sys.exit(0)

        cwd = hook_input.get("cwd", os.getcwd())

    cwd = Path(cwd or os.getcwd())
    project_root = cwd  # Assume cwd is the project root

    # --- Find SKILL.md ---
    skill_md = find_skill_md(skill_name, project_root)
    if not skill_md:
        sys.exit(0)

    # --- In hook mode, check if outputs exist yet ---
    # PostToolUse:Skill fires when the skill prompt is LOADED, not after the
    # agent finishes executing it.  If the skill's WRITES paths don't exist
    # yet, the skill hasn't produced output — skip validation silently.
    if not parse_cli_arg("--skill"):  # hook mode (stdin)
        writes = extract_writes(skill_md)
        if writes and not any((cwd / w).exists() for w in writes):
            sys.exit(0)

    # --- Find and run compiled validator ---
    compiled = find_compiled_validator(skill_name, project_root)
    if not compiled:
        print(
            f"⚠ No compiled validator for '{skill_name}'. "
            f"Run /compile-validators {skill_name} to generate one.",
            file=sys.stderr, flush=True,
        )
        sys.exit(0)

    start = time.time()
    print(
        f"⚡ Running compiled validator for '{skill_name}'...",
        file=sys.stderr, flush=True,
    )
    result = run_compiled_validator(compiled, cwd)
    elapsed_ms = int((time.time() - start) * 1000)

    if result is None:
        print(
            f"  ⚠ Compiled validator failed ({elapsed_ms}ms)",
            file=sys.stderr, flush=True,
        )
        sys.exit(1)

    print(
        f"  ✓ Compiled validator finished in {elapsed_ms}ms",
        file=sys.stderr, flush=True,
    )

    skipped_rules = result.get("skipped_rules", [])

    if semantic and skipped_rules and result.get("verdict") == "PASS":
        # Structural passed — chain semantic LLM validation for skipped rules
        format_compiled_result(result, skill_md, exit_after=False)
        run_semantic_validation(
            skipped_rules, skill_name, skill_md, cwd,
            model=model, timeout=claude_timeout,
            max_file_size=max_file_size, verbose=verbose,
        )
        # run_semantic_validation calls sys.exit
    else:
        # No --semantic, or structural failed — report and exit
        format_compiled_result(result, skill_md, exit_after=True)


if __name__ == "__main__":
    main()
